.Dd $Mdocdate$ 
.Dt FVWM section
.Os
.Sh NAME
.Nm Fvwm - F? Virtual Window Manager for X11

TODO include sections as they come :3

.Sh Gnome Compliance
Fvwm attempts to be 
.Tn GNOME
(version 1) compliant. Check 
.Lk http://www.gnome.org 
for what that may mean. To disable
.Tn GNOME
hints for some or all windows, the
.Sx Style
.Sx GnomeIgnoreHints
style can be used.

TODO include sections as they come :3
