.Sh SYNOPSIS
.Nm
.Op -c Ar config-command
.Op -d Ar displayname
.Op -f Ar config-file
.Op Fl r  
.Op -s Ar screen_num
.Op Fl V
.Op -C Ar visual-class
.Op -I Ar visual-id
.Op -l Ar colors
.Op Fl L
.Op Fl A
.Op Fl S
.Op Fl P
.Op Fl D
.Op Fl h
.Op -i Ar client-id
.Op -F Ar state-file
.Op --debug-stack-ring
.Op --blackout
