.\"
.\" Please keep file format as follows:
.\" -- Lines should be no longer than 75 characters
.\" -- All nested structures should be commented at their beginning and end
.\" -- All codeblocks should be commented at their beginning and end
.\" -- If the file contains a lot of formatting, keep paragraphs or other 
.\"    logical parts separated by a commented out line and/or comment their
.\"    beginnings and ends
.\" 
.\"  For vim users:
.\" 
.\"  au BufNewFile,BufRead *.mdoc set filetype=groff
.\"  au BufNewFile,BufRead *.mdoc match ErrorMsg '\%>75v.\+'
.\"
.Sh Use on Multi-Screen Displays</title>
If the
.Sy -s
command line argument is not given, 
.Nm
automatically starts up on every 
screen on the specified display. After 
.Nm
starts each screen is treated 
independently. Restarts of 
.Nm
need to be performed separately on each 
screen. The use of
.\" BEGIN CODEBLOCK
.Bd -literal -offset indent -compact
EdgeScroll 0 0
.\" END CODEBLOCK
.Ed
is strongly recommended for multi-screen displays. You may need to quit on 
each screen to quit from the X session completely. This is not to be 
confused with Xinerama support.
