.\"
.\" Please keep file format as follows:
.\" -- Lines should be no longer than 75 characters
.\" -- All nested structures should be commented at their beginning and end
.\" -- All codeblocks should be commented at their beginning and end
.\" -- If the file contains a lot of formatting, keep paragraphs or other 
.\"    logical parts separated by a commented out line and/or comment their
.\"    beginnings and ends
.\" 
.\"  For vim users:
.\" 
.\"  au BufNewFile,BufRead *.mdoc set filetype=groff
.\"  au BufNewFile,BufRead *.mdoc match ErrorMsg '\%>75v.\+'
.\"
.Sh SYNOPSIS
.Nm
.Op -c Ar config-command
.Op -d Ar displayname
.Op -f Ar config-file
.Op Fl r  
.Op -s Ar screen_num
.Op Fl V
.Op -C Ar visual-class
.Op -I Ar visual-id
.Op -l Ar colors
.Op Fl L
.Op Fl A
.Op Fl S
.Op Fl P
.Op Fl D
.Op Fl h
.Op -i Ar client-id
.Op -F Ar state-file
.Op --debug-stack-ring
.Op --blackout
